theme: jekyll-theme-cayman
title: Multi-Label Image Classification via Knowledge Distillation from Weakly-Supervised Detection
description: Yongcheng Liu, Lu Sheng, Jing Shao, Junjie Yan, Shiming Xiang, Chunhong Pan
show_downloads: true
